### ISSUE TITLE
How about BeST Address?

### ISSUE THREAD

**Issue by haiduong87** [geo6/api#181]
Hi geo6,

Are you going to use BeST Address as the only one data-source for geocoding?

Here it is
https://www.geo.be/catalog/details/ca0fd5c0-8146-11e9-9012-482ae30f98d9?l=en

Thank you!

Duong Nguyen

**Comment by jbelien** [comment]
Hello @haiduong87 

I'm currently not using BeST Address and I'm not planning to for now but the sources for the addresses we use (see https://github.com/geo6/api#address) are exactly the same as the sources used by BeST Address.
I'm just processing the original sources instead of using addresses processed by BeST but the resulting addresses dataset should be (almost) identical.

**Comment by haiduong87** [comment]
I see,

Thank you!
